apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 443
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: YOUR_DOCKERHUB_USERNAME/hello-python:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
